# SPDX-License-Identifier: GPL-2.0-only
[package]
name = "bpf-kcrypto"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[workspace]

[[bin]]
name = "kcrypto"
path = "src/bin/kcrypto.rs"

[dependencies]
aya-ebpf = "=0.2.1"
kryprobe-abi = { path = "../kryprobe-abi" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
