# SPDX-License-Identifier: GPL-3.0-or-later
[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
goblin = "0.10"
kryprobe-core.workspace = true
kryprobe-privilege.workspace = true
libc = "0.2"
serde_json = "1"

[dev-dependencies]
kryprobe-testkit.workspace = true

[lints]
workspace = true
