# SPDX-License-Identifier: GPL-3.0-or-later
[package]
name = "kryprobe-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
kryprobe-abi.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
kryprobe-report.workspace = true
kryprobe-testkit.workspace = true
proptest = "1.11.0"

[lints]
workspace = true
