# SPDX-License-Identifier: GPL-3.0-or-later
[package]
name = "kryprobe-core"
version = "0.0.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
kryprobe-abi = { path = "../kryprobe-abi" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
kryprobe-report = { path = "../kryprobe-report" }
kryprobe-testkit = { path = "../kryprobe-testkit" }
