// SPDX-License-Identifier: GPL-3.0-or-later
//! Required payload keys per record kind (frozen schema `required` tables).

/// Required payload keys per record kind (frozen schema `required` tables).
pub(super) const KIND_TABLE: &[(&str, &[&str])] = &[
    (
        "session_start",
        &[
            "target_selector",
            "capture_mode",
            "requested_backends",
            "contract_version",
            "qualification_id",
        ],
    ),
    (
        "implementation_catalog",
        &[
            "implementation_id",
            "backend",
            "object_id",
            "profile_id",
            "safe_name",
            "resolution",
            "provenance_record_ids",
        ],
    ),
    (
        "operation_observation",
        &[
            "observation_id",
            "target_id",
            "implementation_id",
            "backend",
            "boundary",
            "phase",
            "call_kind",
            "operation_class",
            "outcome",
            "native_namespace",
            "native_operation",
            "native_result",
            "algorithm",
            "duration_ns",
        ],
    ),
    (
        "coverage_gap",
        &[
            "target_id",
            "backend",
            "dimension",
            "reason",
            "begin_ns",
            "end_ns",
            "impact",
            "omitted_count",
        ],
    ),
    (
        "aggregate_snapshot",
        &[
            "target_id",
            "backend",
            "implementation_id",
            "unit",
            "count",
            "count_integrity",
            "begin_ns",
            "end_ns",
            "final",
            "barrier_status",
            "event_integrity",
        ],
    ),
    (
        "relationship",
        &[
            "parent_observation_id",
            "child_observation_id",
            "relation",
            "anchor",
            "rule_id",
            "integrity",
        ],
    ),
    (
        "session_end",
        &[
            "verdict",
            "final_barrier",
            "unresolved_gap_ids",
            "child_exit_code",
            "child_signal",
        ],
    ),
];
